### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bigorangemachine** [bigorangemachine/ksp-kronalutils#14]
#### Version 0.24.x (KSP Version Sync) Targets:
- [ ] [Bug Fix] Get UI flow so its impossible to save broken ships (a lot of work)
- [ ] [Bug Fix] Engine fairings don't always disappear/work
- [ ] Explosion/Separation factor should be controlled by a dial
- [ ] Independent preview window
- [ ] [Bug Fix] Moving the vessel away from the 0,0,0 position will cause the dials not to work correctly
- [ ] Settings/Dials persistence (save state of dials/settings based off saved file/vessel)
- [x] Vessel Rotation buttons decreased increments
- [x] Generally using the GitHub Issues to keep track
#### Wish List:
- [ ] SVG/WebGL export
- [ ] Vessel Data Export (Text/JSON/XML file) which would be integrated with KSP Engineer
- [ ] Screenshot Vessels outside editor(s)
- [ ] Set dials to different settings based on presets (Menu/Save&Load?)
- [ ] Make all dials make sense (if possible) and some are glitchy
- [x] [Bug Fix] Bottom left square of preview is discoloured
#### High Priority Improvements:
- [ ] Stability/UI flow to create stability
- [x] White Line Artifacts (Images over ~4000px in height)
- [ ] Kerbal Stuff Version checking
- [ ] Part Explosion/Separation & visibility made generic/hookable/right-click-menu'd (modded parts need to be accounted for rather than waiting for people to contribute)
#### Other Improvements
- [ ] Staging on/off detection
- [ ] PWings & Procedural Parts
- [ ] Use Extents instead of Size for farClip 
- [ ] ProcFairingHide modify to remove facing fairings 
- [ ] Procfairing, auto-lock shape or stay locked if already 
- [ ] Make new proc fairing hide-all 
- [ ] Culling for SPH (Background)
